# Generated by Django 3.1.5 on 2021-02-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210217_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='dailyBudget',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
