# Generated by Django 3.1.5 on 2021-02-25 10:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210217_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileId', models.CharField(db_index=True, max_length=100)),
                ('adId', models.CharField(max_length=100)),
                ('campaignId', models.CharField(db_index=True, max_length=100)),
                ('adGroupId', models.CharField(db_index=True, max_length=100)),
                ('sku', models.CharField(max_length=200)),
                ('asin', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileId', models.CharField(db_index=True, max_length=100)),
                ('targetId', models.CharField(max_length=100)),
                ('campaignId', models.CharField(db_index=True, max_length=100)),
                ('adGroupId', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('expression', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
                ('resolvedExpression', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
                ('expressionType', models.CharField(max_length=50)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
        ),
    ]
