# Generated by Django 3.1.5 on 2021-02-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_productads_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='portfolioId',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
