# Generated by Django 3.1.5 on 2021-03-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210225_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegativeSearchtermLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileId', models.CharField(db_index=True, max_length=100)),
                ('campaignId', models.CharField(db_index=True, max_length=100)),
                ('adGroupId', models.CharField(db_index=True, max_length=100)),
                ('targetId', models.CharField(db_index=True, max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('campaignName', models.CharField(max_length=200)),
                ('adGroupName', models.CharField(max_length=200)),
                ('query', models.CharField(max_length=200)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('orders', models.IntegerField(default=0)),
                ('spends', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
        ),
    ]
