# Generated by Django 3.1.5 on 2021-03-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_optimizesearchtermlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileId', models.CharField(db_index=True, max_length=100)),
                ('countryCode', models.CharField(max_length=20)),
                ('currencyCode', models.CharField(max_length=20)),
                ('sku', models.CharField(max_length=50)),
                ('asin', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('macs', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
        ),
    ]
