# Generated by Django 3.1.5 on 2021-03-08 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_shopproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignStructChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileId', models.CharField(db_index=True, max_length=100)),
                ('changeLog', models.TextField()),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
