# Generated by Django 3.1.5 on 2021-03-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_campaignstructchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroup',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
