# Generated by Django 3.1.5 on 2021-03-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_target_expressionvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstructchangelog',
            name='type',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
