# Generated by Django 3.1.5 on 2021-03-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_campaignstructchangelog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
