# Generated by Django 3.1.5 on 2021-04-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
