# Generated by Django 3.1.5 on 2021-04-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_shop_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproducts',
            name='promotionTarget',
            field=models.IntegerField(default=0),
        ),
    ]
