# Generated by Django 3.1.5 on 2021-05-23 15:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210523_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignNegativeKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileId', models.CharField(db_index=True, max_length=100)),
                ('campaignId', models.CharField(db_index=True, max_length=100)),
                ('keywordId', models.CharField(max_length=100)),
                ('keywordText', models.CharField(max_length=200)),
                ('matchType', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NegativeKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileId', models.CharField(db_index=True, max_length=100)),
                ('campaignId', models.CharField(db_index=True, max_length=100)),
                ('adGroupId', models.CharField(db_index=True, max_length=100)),
                ('keywordId', models.CharField(max_length=100)),
                ('keywordText', models.CharField(max_length=200)),
                ('matchType', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NegativeTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileId', models.CharField(db_index=True, max_length=100)),
                ('campaignId', models.CharField(db_index=True, max_length=100)),
                ('adGroupId', models.CharField(db_index=True, max_length=100)),
                ('targetId', models.CharField(max_length=100)),
                ('expression', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
                ('resolvedExpression', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
                ('expressionType', models.CharField(max_length=50)),
                ('expressionValue', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='keywordFormat',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
