# Generated by Django 3.1.5 on 2021-07-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_shopproducts_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproducts',
            name='target',
            field=models.IntegerField(default=0),
        ),
    ]
