# Generated by Django 3.1.5 on 2021-07-18 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_shopproducts_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileId', models.CharField(db_index=True, max_length=100)),
                ('sku', models.CharField(max_length=50)),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('impressions', models.IntegerField(default=-1)),
                ('clicks', models.IntegerField(default=-1)),
                ('orders', models.IntegerField(default=-1)),
                ('points', models.FloatField(default=-1.0)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
