# Generated by Django 3.1.5 on 2021-07-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210719_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsrecord',
            name='cost',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='productsrecord',
            name='sales',
            field=models.IntegerField(default=-1),
        ),
    ]
