# Generated by Django 3.1.5 on 2021-07-26 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210723_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproducts',
            name='target',
        ),
    ]
