# Generated by Django 3.1.5 on 2021-09-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_shopproducts_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='region',
            field=models.CharField(default='US', max_length=200),
        ),
    ]
