# Generated by Django 3.1.5 on 2021-09-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210907_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='deposite',
            field=models.BooleanField(default=True),
        ),
    ]
